name: Draft PDF

on:
  push:
    paths:
      - paper.md
      - paper.bib
      - .github/workflows/draft-pdf.yml
      - assets/**
  workflow_dispatch:

jobs:
  paper:
    name: Paper Draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@v1
        with:
          journal: joss
          paper-path: paper.md

      - name: Upload compiled PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf
