name: Draft PDF

on:
  push:
    paths:
      - paper.md
      - paper.bib
      - .github/workflows/draft-pdf.yml
      - assets/**
  workflow_dispatch:

permissions:
  contents: write

jobs:
  paper:
    name: Paper Draft
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper.md

      - name: Upload compiled PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf

      - name: Commit PDF to repository
        uses: EndBug/add-and-commit@v9
        with:
          message: '(auto) Update paper PDF draft'
          add: 'paper.pdf'
